version: '3.3' # specify docker-compose version

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
      -
  mongo:
    image: mongo:3.4
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    command: --smallfiles --rest
#   command: --smallfiles --rest --auth

volumes:
  mongodata: