AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.sensiblemetrics.api.sqoola::sqoola-parent
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  CascoderCommonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.sensiblemetrics.api.sqoola.common.handler.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/cascoder-parent-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SqoolaCommonApi:
    Description: URLConstraint for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SqoolaCommonApi
